$id: https://spec.openapis.org/oas/3.2/meta/WORK-IN-PROGRESS
$schema: https://json-schema.org/draft/2020-12/schema

title: OAS Base Vocabulary
description: A JSON Schema Vocabulary used in the OpenAPI JSON Schema Dialect

$dynamicAnchor: meta

$vocabulary:
  https://spec.openapis.org/oas/3.2/vocab/base: true

type:
  - object
  - boolean
properties:
  discriminator:
    $ref: '#/$defs/discriminator'
  example: true
  externalDocs:
    $ref: '#/$defs/external-docs'
  xml:
    $ref: '#/$defs/xml'

$defs:
  discriminator:
    $ref: '#/$defs/extensible'
    properties:
      mapping:
        additionalProperties:
          type: string
        type: object
      defaultMapping:
        type: string
      propertyName:
        type: string
    required:
      - propertyName
    type: object
    unevaluatedProperties: false

  extensible:
    patternProperties:
      ^x-: true
  external-docs:
    $ref: '#/$defs/extensible'
    properties:
      description:
        type: string
      url:
        format: uri-reference
        type: string
    required:
      - url
    type: object
    unevaluatedProperties: false

  xml:
    $ref: '#/$defs/extensible'
    properties:
      nodeType:
        type: string
        enum:
          - element
          - attribute
          - text
          - cdata
          - none
      name:
        type: string
      namespace:
        format: iri
        type: string
      prefix:
        type: string
      attribute:
        type: boolean
      wrapped:
        type: boolean
    type: object
    dependentSchemas:
      nodeType:
        properties:
          attribute: false
          wrapped: false
    unevaluatedProperties: false
