$id: https://spec.openapis.org/oas/3.1/meta/WORK-IN-PROGRESS
$schema: https://json-schema.org/draft/2020-12/schema

title: OAS Base Vocabulary
description: A JSON Schema Vocabulary used in the OpenAPI Schema Dialect

$dynamicAnchor: meta

$vocabulary:
  https://spec.openapis.org/oas/3.1/vocab/base: true

type:
  - object
  - boolean
properties:
  discriminator:
    $ref: '#/$defs/discriminator'
  example: true
  externalDocs:
    $ref: '#/$defs/external-docs'
  xml:
    $ref: '#/$defs/xml'

$defs:
  discriminator:
    $ref: '#/$defs/extensible'
    properties:
      mapping:
        additionalProperties:
          type: string
        type: object
      propertyName:
        type: string
    required:
      - propertyName
    type: object
    unevaluatedProperties: false

  extensible:
    patternProperties:
      ^x-: true
  external-docs:
    $ref: '#/$defs/extensible'
    properties:
      description:
        type: string
      url:
        format: uri-reference
        type: string
    required:
      - url
    type: object
    unevaluatedProperties: false

  xml:
    $ref: '#/$defs/extensible'
    properties:
      attribute:
        type: boolean
      name:
        type: string
      namespace:
        format: uri
        type: string
      prefix:
        type: string
      wrapped:
        type: boolean
    type: object
    unevaluatedProperties: false
